
const payBtn = document.getElementById('payBtn')
payBtn.addEventListener('click', () => {
    postPayment()
})

async function postPayment() {
    const payInput = parseInt(document.getElementById('payInput').value)
    const payCurrency = "PHP"
    
    if(payInput && payInput > 0) {
        // Prepare data to send
        const data = { 
                    totalAmount: {
                        value: payInput, 
                        currency: payCurrency
                    },
                    redirectUrl: { //should change to your response pages
                        success: 'http://localhost/payment-test/success.php',
                        //failure: 'https://www.mechantsite.com/failure?id=5fc10b93-bdbd-4f31-b31d-4575a3785009',
                        failure: 'http://localhost/payment-test/failed.php',
                        cancel: 'http://localhost/payment-test/cancelled.php'
                    },
                    //should be generated by the business website
                    requestReferenceNumber: '5fc10b93-bdbd-4f31-b31d-4575a3785009',
                    buyer: {
                        contact: {email: 'vincent@gmail.com'},
                        firstName: 'vincent',
                        middleName: 'd',
                        lastName: 'tan',
                        birthday: '1994-01-30', //this is the required date format
                        sex: 'M',
                    },
                    items: [
                    {
                        amount: {value: 1000},
                        totalAmount: {value: 1000},
                        name: 'Cheque',
                        quantity: '1'
                    },
                    {
                        amount: {value: 1}, 
                        totalAmount: {value: 2}, 
                        name: 'coins', 
                        quantity: '2'
                    },
                    ],
        }

        try {
            // Send POST request using fetch
            const response = await fetch('https://pg-sandbox.paymaya.com/checkout/v1/checkouts', {
                method: 'POST',
                headers: {
                    accept: 'application/json',
                    'content-type': 'application/json',
                    authorization: 'Basic cGstWjBPU3pMdkljT0kyVUl2RGhkVEdWVmZSU1NlaUdTdG5jZXF3VUU3bjBBaDo=',
                },
                body: JSON.stringify(data)
            })

            // Handle the response
            const result = await response.json()
            console.log(result)
            if(response.status === 200) {
                setTimeout(() => {
                    window.location.href = result.redirectUrl
                }, 50)
            }

        } catch (error) {
            console.error('Error:', error)
        }
    } else 
        alert('Invalid Payment Input')
}